server:
  port: 4004
#  servlet:
#    context-path: /test


spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/springboot"
    username: root
    password: baynhet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  mandatory-file-encoding: UTF-8
  mail:
    default-encoding: UTF-8
storage:
location: D:/upload